import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="layout">
          <header className="layout-header">
            <h1>Dental Clinic</h1>
          </header>
          <main>{children}</main>
          <footer className="layout-footer">
            <p>&copy; 2023 Dental Clinic. All rights reserved.</p>
          </footer>
          <style jsx>{`
            .layout {
              font-family: 'Arial', sans-serif;
              color: #333;
            }
            .layout-header {
              background-color: #007bff;
              color: white;
              padding: 10px;
              text-align: center;
            }
            .layout-footer {
              text-align: center;
              padding: 10px;
              background-color: #f1f1f1;
            }
          `}</style>
        </div>
      </body>
    </html>
  );
}
